### ISSUE TITLE
 Unable to instantiate application 

### ISSUE THREAD

**Issue by 1136346879** [youxiachai/tinker-new-sample-android#1]
大佬 你好： 
1.9.14.7   Unable to instantiate application 
  java.lang.RuntimeException: Unable to instantiate application com.xfs.fsyuncai.logic.TinkerFSYCApplication: java.lang.ClassNotFoundException: Didn't find class "com.xfs.fsyuncai.logic.TinkerFSYCApplication" on path: DexPathList[[zip file "/system/framework/org.apache.http.legacy.boot.jar", zip file "/data/app/com.xfs.fsyuncai-96B-4NvjAKR272ThMvp7_Q==/base.apk"],nativeLibraryDirectories=[/data/app/com.xfs.fsyuncai-96B-4NvjAKR272ThMvp7_Q==/lib/arm64, /data/app/com.xfs.fsyuncai-96B-4NvjAKR272ThMvp7_Q==/base.apk!/lib/arm64-v8a, /system/lib64]]
        at android.app.LoadedApk.makeApplication(LoadedApk.java:1084)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6171)
        at android.app.ActivityThread.access$1200(ActivityThread.java:236)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1851)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:224)
        at android.app.ActivityThread.main(ActivityThread.java:7042)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:536)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:868)
     Caused by: java.lang.ClassNotFoundException: Didn't find class "com.xfs.fsyuncai.logic.TinkerFSYCApplication" on path: DexPathList[[zip file "/system/framework/org.apache.http.legacy.boot.jar", zip file "/data/app/com.xfs.fsyuncai-96B-4NvjAKR272ThMvp7_Q==/base.apk"],nativeLibraryDirectories=[/data/app/com.xfs.fsyuncai-96B-4NvjAKR272ThMvp7_Q==/lib/arm64, /data/app/com.xfs.fsyuncai-96B-4NvjAKR272ThMvp7_Q==/base.apk!/lib/arm64-v8a, /system/lib64]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:134)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at android.app.AppComponentFactory.instantiateApplication(AppComponentFactory.java:50)
        at androidx.core.app.CoreComponentFactory.instantiateApplication(CoreComponentFactory.java:47)
        at android.app.Instrumentation.newApplication(Instrumentation.java:1124)
        at android.app.LoadedApk.makeApplication(LoadedApk.java:1076)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6171) 
        at android.app.ActivityThread.access$1200(ActivityThread.java:236) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1851) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:224) 
        at android.app.ActivityThread.main(ActivityThread.java:7042) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:536) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:868) 

![image](https://user-images.githubusercontent.com/15826462/89115663-885e2480-d4bd-11ea-9193-b150eae4eb3f.png)
我用的demo   gradle 3.5.3  对应   6.1.1  没问题 
项目中 gradle 3.5.3  对应   5.4.1   就会报这个错误， 这个必须是6.1.1  吗？

**Comment by youxiachai** [comment]
`Didn't find class "com.xfs.fsyuncai.logic.TinkerFSYCApplication" ` 跟gradle 版本没关系.. 是你的`annotationProcessor` 没设置好,导致那个类没生成出来,你可以看看你的apk 是不是真的没这个类,

这个查一下你的tinker的接入....这个是你的tinker 没接好,导致那个类没生成出来

**Comment by youxiachai** [comment]
跟demo无关，关掉了

**Comment by 1136346879** [comment]
嗯  跟demo无关 解决了  谢谢
